parameters:
    module_settings:
        configuration:
            - title: "Titulo de prueba"
            - avatar: "avatar.jpg"

        hooks:
              - "actionDispatcherBefore"

        tabs:
              - {
                    name: "Skeleton",
                    parent_class_name: "AdminParentModulesSf",
                    class_name: "AdminSkeletonTab",
                    visible: false,
                }
              - {
                    name: "Info",
                    parent_class_name: "AdminSkeletonTab",
                    class_name: "AdminSkeletonInfo",
                }

services:
    _defaults:
        public: true

    skeleton.module:
        class: "Skeleton"
        factory: ["Module", "getInstanceByName"]
        arguments:
            - "skeleton"

    #    Installers
    install.tab:
        class: 'veiss\Skeleton\Install\Tab'
        arguments:
            - "%module_settings%"

    installer:
        class: 'veiss\Skeleton\Install\Installer'
        arguments:
            - "@skeleton.module"
            - "%module_settings%"

    uninstaller:
        class: 'veiss\Skeleton\Install\Uninstaller'
        arguments:
            - "@skeleton.module"
            - "%module_settings%"
